### ISSUE TITLE
Create instructions for building on Windows

### ISSUE THREAD

**Issue by yortus** [paypac/node-concierge#14]
Tried to do a fresh install but got the following error. Looks like a problem building native module `ursa`.

- Windows 10
- Node 6.2 and Node 6.7 (both gave same failure)

```
> ursa@0.9.4 install V:\paypac\node-concierge\node_modules\ursa
> node-gyp rebuild


V:\paypac\node-concierge\node_modules\ursa>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  ursaNative.cc
..\src\ursaNative.cc(157): warning C4244: 'argument': conversion from 'ssize_t' to 'int', possible loss of data [V:\paypac\node-concierge\node_modules\ursa\bui
ld\ursaNative.vcxproj]
..\src\ursaNative.cc(172): warning C4244: 'argument': conversion from 'ssize_t' to 'int', possible loss of data [V:\paypac\node-concierge\node_modules\ursa\bui
ld\ursaNative.vcxproj]
..\src\ursaNative.cc(378): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [V:\paypac\node-concierge\node_modules\ursa\
build\ursaNative.vcxproj]
..\src\ursaNative.cc(379): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [V:\paypac\node-concierge\node_modules\ursa\
build\ursaNative.vcxproj]
..\src\ursaNative.cc(686): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [V:\paypac\node-concierge\node_modules\ursa\buil
d\ursaNative.vcxproj]
..\src\ursaNative.cc(734): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [V:\paypac\node-concierge\node_modules\ursa\buil
d\ursaNative.vcxproj]
..\src\ursaNative.cc(779): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [V:\paypac\node-concierge\node_modules\ursa\buil
d\ursaNative.vcxproj]
..\src\ursaNative.cc(826): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [V:\paypac\node-concierge\node_modules\ursa\buil
d\ursaNative.vcxproj]
..\src\ursaNative.cc(945): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data [V:\paypac\node-concierge\node_modules\
ursa\build\ursaNative.vcxproj]
..\src\ursaNative.cc(1003): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data [V:\paypac\node-concierge\node_modules
\ursa\build\ursaNative.vcxproj]
  win_delay_load_hook.c
LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win64\lib\libeay32.lib' [V:\paypac\node-concierge\node_modules\ursa\build\ursaNative.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd V:\paypac\node-concierge\node_modules\ursa
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:ursa@0.9.4 ursa@0.9.4 install: `node-gyp rebuild`
npm WARN install:ursa@0.9.4 Exit status 1
```

**Comment by Seikho** [comment]
This is the painful part of the `lets-encrypt` stuff. It has a peer-dependency on OpenSSL. I'll investigate an alternative.

**Comment by yortus** [comment]
Hmmm, I thought I installed this a few weeks ago without seeing this problem. Now I'm not sure if I just imagined that...

Do you know any way I can get this working in the mean time? Hacky is fine.

**Comment by Seikho** [comment]
I'm unable to get this working on my surface at the moment.
I'd run it on a Linux Vagrant box for now.

**Comment by Seikho** [comment]
According to the source in `le-tiny-core`, `ursa` is an optional dependency. If the `ursa` build fails, `letsencrypt` will continue to work, but will probably perform slower.
Closing for now. I'll tinker with the Vagrantfile in the future to get the build working _with_ `ursa`.
